version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    expose:
      - 5672
    environment:
      RABBITMQ_DEFAULT_USER: "coldmart"
      RABBITMQ_DEFAULT_PASS: "coldmart"  
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  core:
    build:
      dockerfile: ./src/Coldmart.Core.API/Dockerfile
    ports:
      - "8082:8080"
    expose:
      - 8082
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  alunos:
    build:
      dockerfile: ./src/Coldmart.Alunos.API/Dockerfile
    ports:
      - "8083:8080"
    expose:
      - 8083
    depends_on:
      core:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  pagamentos:
    build:
      dockerfile: ./src/Coldmart.Pagamentos.API/Dockerfile
    ports:
      - "8084:8080"
    expose:
      - 8084
    depends_on:
      alunos: #Feito para evitar concorrencia com as migracoes
        condition: service_started
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  cursos:
    build:
      dockerfile: ./src/Coldmart.Cursos.API/Dockerfile
    ports:
      - "8085:8080"
    expose:
      - 8085
    depends_on:
      pagamentos: #Feito para evitar concorrencia com as migracoes
        condition: service_started
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

networks:
  default:
    driver: bridge